language: java
matrix:
  include:
    - jdk: oraclejdk8
script: travis_retry ./gradlew clean headless allTests coverage coveralls -Pconfig="config_test.json" -i
before_install:
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"

addons:
  apt:
    packages:
      - oracle-java8-installer

