language: java
matrix:
  include:
    - jdk: oraclejdk8
script: ./gradlew clean guiTests --tests guitests.PersonEditGuiTest coverage coveralls -i
before_install:
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"

after_failure:
    - "for i in *.png; do curl --upload-file $i https://transfer.sh/$i; done"

addons:
  apt:
    packages:
      - oracle-java8-installer

