language: java
matrix:
  include:
    - env: TESTTYPE=headless
      jdk: oraclejdk8
    - env: TESTTYPE=headful
      jdk: oraclejdk8
script: travis_retry ./gradlew clean $TESTTYPE jacocoRootReport coveralls

before_install:
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"

addons:
  apt:
    packages:
      - oracle-java8-installer

