language: java
matrix:
  include:
    - jdk: oraclejdk8
script: travis_retry ./gradlew clean headless allTests coverage coveralls -i
before_install:
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"
          - "sudo wget https://github.com/HubTurbo/addressbook/releases/download/Resources/jxbrowser-6.4.jar -P /lib"
          - "sudo wget https://github.com/HubTurbo/addressbook/releases/download/Resources/jxbrowser-linux32-6.4.jar -P /lib"
          - "sudo wget https://github.com/HubTurbo/addressbook/releases/download/Resources/jxbrowser-linux64-6.4.jar -P /lib"
          - "sudo wget https://github.com/HubTurbo/addressbook/releases/download/Resources/jxbrowser-win-6.4.jar -P /lib"
          - "sudo wget https://github.com/HubTurbo/addressbook/releases/download/Resources/jxbrowser-mac-6.4.jar -P /lib"

addons:
  apt:
    packages:
      - oracle-java8-installer

